CREATE TABLE "account" (
	"userId" text NOT NULL,
	"type" text NOT NULL,
	"provider" text NOT NULL,
	"providerAccountId" text NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" text,
	"scope" text,
	"id_token" text,
	"session_state" text,
	CONSTRAINT "account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "api_cache" (
	"cache_key" text PRIMARY KEY NOT NULL,
	"body" text NOT NULL,
	"expires_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "applications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "applications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" integer NOT NULL,
	"applicant_user_id" text NOT NULL,
	"character_id" integer NOT NULL,
	"message" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" text NOT NULL,
	"decided_at" text
);
--> statement-breakpoint
CREATE TABLE "boss_clears" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "boss_clears_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"snapshot_id" integer NOT NULL,
	"character_id" integer NOT NULL,
	"week_start" text NOT NULL,
	"boss" text NOT NULL,
	"difficulty" text NOT NULL,
	"cycle" text NOT NULL,
	"registered" boolean NOT NULL,
	"completed" boolean NOT NULL,
	"list_order_no" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "characters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "characters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ocid" text NOT NULL,
	"name" text NOT NULL,
	"world" text,
	"class" text,
	"level" integer,
	"image_url" text,
	"owner_user_id" text,
	"account_id" text,
	"hidden" boolean DEFAULT false NOT NULL,
	"cur_power" bigint,
	"cur_power_at" text,
	"cur_setup_hashes" jsonb,
	"best_power" bigint,
	"best_power_at" text,
	"best_setup_hash" text,
	"arcane_force" integer,
	"authentic_force" integer,
	"force_fetched_at" text,
	"superseded_by" integer,
	"basic_fetched_at" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "characters_ocid_unique" UNIQUE("ocid")
);
--> statement-breakpoint
CREATE TABLE "job_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "job_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_name" text NOT NULL,
	"started_at" text NOT NULL,
	"finished_at" text,
	"status" text DEFAULT 'running' NOT NULL,
	"stats" jsonb,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "nexon_keys" (
	"user_id" text PRIMARY KEY NOT NULL,
	"enc_key" text NOT NULL,
	"key_hint" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"account_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"last_ok_at" text,
	"last_error" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "parties" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parties_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_user_id" text NOT NULL,
	"name" text,
	"boss" text NOT NULL,
	"difficulty" text NOT NULL,
	"world" text,
	"schedule_note" text,
	"day_of_week" integer,
	"hour" integer,
	"minute" integer,
	"repeats" boolean DEFAULT true NOT NULL,
	"week_start" text,
	"memo" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "party_members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "party_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"party_id" integer NOT NULL,
	"nickname" text NOT NULL,
	"character_id" integer,
	"is_leader" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plan_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "plan_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"world" text NOT NULL,
	"config" jsonb NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"author_user_id" text NOT NULL,
	"party_id" integer,
	"boss" text NOT NULL,
	"difficulty" text NOT NULL,
	"world" text,
	"title" text NOT NULL,
	"body" text,
	"slots" integer DEFAULT 1 NOT NULL,
	"min_power" bigint,
	"schedule_note" text,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "power_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "power_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"character_id" integer NOT NULL,
	"power" bigint NOT NULL,
	"setup_hash" text,
	"measured_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scheduler_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scheduler_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"character_id" integer NOT NULL,
	"snapshot_date" text NOT NULL,
	"kind" text NOT NULL,
	"week_start" text NOT NULL,
	"weekly_clear_count" integer DEFAULT 0 NOT NULL,
	"weekly_limit" integer DEFAULT 12 NOT NULL,
	"raw" jsonb NOT NULL,
	"fetched_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"sessionToken" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"expires" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"email" text,
	"emailVerified" timestamp,
	"image" text,
	"created_at" text NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verificationToken" (
	"identifier" text NOT NULL,
	"token" text NOT NULL,
	"expires" timestamp NOT NULL,
	CONSTRAINT "verificationToken_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "applications" ADD CONSTRAINT "applications_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "applications" ADD CONSTRAINT "applications_applicant_user_id_user_id_fk" FOREIGN KEY ("applicant_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "applications" ADD CONSTRAINT "applications_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "boss_clears" ADD CONSTRAINT "boss_clears_snapshot_id_scheduler_snapshots_id_fk" FOREIGN KEY ("snapshot_id") REFERENCES "public"."scheduler_snapshots"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "boss_clears" ADD CONSTRAINT "boss_clears_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "characters" ADD CONSTRAINT "characters_owner_user_id_user_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nexon_keys" ADD CONSTRAINT "nexon_keys_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parties" ADD CONSTRAINT "parties_owner_user_id_user_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "party_members" ADD CONSTRAINT "party_members_party_id_parties_id_fk" FOREIGN KEY ("party_id") REFERENCES "public"."parties"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "party_members" ADD CONSTRAINT "party_members_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plan_configs" ADD CONSTRAINT "plan_configs_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_author_user_id_user_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_party_id_parties_id_fk" FOREIGN KEY ("party_id") REFERENCES "public"."parties"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "power_log" ADD CONSTRAINT "power_log_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scheduler_snapshots" ADD CONSTRAINT "scheduler_snapshots_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "api_cache_expires_idx" ON "api_cache" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "applications_unique" ON "applications" USING btree ("post_id","character_id");--> statement-breakpoint
CREATE INDEX "applications_post_idx" ON "applications" USING btree ("post_id","status");--> statement-breakpoint
CREATE INDEX "applications_user_idx" ON "applications" USING btree ("applicant_user_id");--> statement-breakpoint
CREATE INDEX "boss_clears_char_week_idx" ON "boss_clears" USING btree ("character_id","week_start");--> statement-breakpoint
CREATE INDEX "boss_clears_boss_idx" ON "boss_clears" USING btree ("boss","difficulty","week_start");--> statement-breakpoint
CREATE INDEX "characters_name_idx" ON "characters" USING btree ("name");--> statement-breakpoint
CREATE INDEX "characters_owner_idx" ON "characters" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "characters_world_idx" ON "characters" USING btree ("world");--> statement-breakpoint
CREATE INDEX "job_runs_name_idx" ON "job_runs" USING btree ("job_name","started_at");--> statement-breakpoint
CREATE INDEX "parties_owner_idx" ON "parties" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "parties_boss_idx" ON "parties" USING btree ("boss","difficulty");--> statement-breakpoint
CREATE UNIQUE INDEX "party_members_unique" ON "party_members" USING btree ("party_id","nickname");--> statement-breakpoint
CREATE INDEX "party_members_nick_idx" ON "party_members" USING btree ("nickname");--> statement-breakpoint
CREATE INDEX "party_members_char_idx" ON "party_members" USING btree ("character_id");--> statement-breakpoint
CREATE UNIQUE INDEX "plan_configs_unique" ON "plan_configs" USING btree ("user_id","world");--> statement-breakpoint
CREATE INDEX "posts_status_idx" ON "posts" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "posts_boss_idx" ON "posts" USING btree ("boss","difficulty");--> statement-breakpoint
CREATE INDEX "posts_author_idx" ON "posts" USING btree ("author_user_id");--> statement-breakpoint
CREATE INDEX "power_log_char_idx" ON "power_log" USING btree ("character_id","measured_at");--> statement-breakpoint
CREATE UNIQUE INDEX "sched_snap_unique" ON "scheduler_snapshots" USING btree ("character_id","snapshot_date","kind");--> statement-breakpoint
CREATE INDEX "sched_snap_week_idx" ON "scheduler_snapshots" USING btree ("character_id","week_start");