CREATE TABLE "item_expiries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "item_expiries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"character_id" integer NOT NULL,
	"source" text NOT NULL,
	"slot" text,
	"name" text NOT NULL,
	"icon" text,
	"expire_at" text NOT NULL,
	"fetched_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notices" (
	"notice_id" integer PRIMARY KEY NOT NULL,
	"kind" text DEFAULT 'event' NOT NULL,
	"title" text NOT NULL,
	"url" text NOT NULL,
	"posted_at" text,
	"event_start" text,
	"event_end" text,
	"is_sunday" boolean DEFAULT false NOT NULL,
	"fetched_at" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "characters" ADD COLUMN "expiry_fetched_at" text;--> statement-breakpoint
ALTER TABLE "item_expiries" ADD CONSTRAINT "item_expiries_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "item_expiries_char_idx" ON "item_expiries" USING btree ("character_id","expire_at");--> statement-breakpoint
CREATE INDEX "item_expiries_expire_idx" ON "item_expiries" USING btree ("expire_at");--> statement-breakpoint
CREATE INDEX "notices_event_range_idx" ON "notices" USING btree ("event_start","event_end");--> statement-breakpoint
CREATE INDEX "notices_kind_idx" ON "notices" USING btree ("kind");